templates/sample.html

Sample Template.

---

scripts/ExtendedCombatHud.js
styles/ActionHUD.css
templates/extendedCombatHud.html

Not a Finalized Style, but it works for HUD sizes.
We can work on a better version, just wanted to push these changes.

Accordion Style Spell Feature List

---

module.json
scripts/ExtendedCombatHud.js
scripts/config.js
styles/ActionHUD.css
styles/CombatHUD.css
styles/ECH.css
styles/PortraitHUD.css
templates/extendedCombatHud.html

-- Extended Combat Hud --
Fixed HUD element preventing user from clicking through empty space to interact with Foundry Canvas
-- Portrait Display --
Added Portrait Display
Added HP Box to Portrait Display
Added AC Box to Portrait Display
Added Player name to Portrait Display
Added Player Levels/Classes to Portrait Display
-- Action Bar --
Added Animation to Features Container (Slides up/down)
Fixed Active state not being added to menu when clicked

Portrait Display

---

styles/PortraitHUD.css
templates/extendedCombatHud.html

-- Portrait --
Changed Stats to be rigged to DataSets to allow easier use of JavaScript to update them

Portrait Stats Rigged To DataSets

---

scripts/ExtendedCombatHud.js

Stupid Scale Function

---

scripts/ExtendedCombatHud.js

-- Action HUD --
Fixed Accordion to only account for items within the menu of the accordion instead of all the items in total.

Accordion Fixed

---

scripts/ExtendedCombatHud.js
scripts/config.js
styles/ActionHUD.css
templates/extendedCombatHud.html

-- Action HUD --
Sorted Spells [ Cantrip, Pact, Levels]
Added Spell Slot Display to Spells Accordion

Spell Slots and Spells

---

styles/ECH.css
styles/PortraitHUD.css
templates/extendedCombatHud.html

-- Movement HUD --
Added Squares for movement. It looks okay I guess

Movement HUD

---

scripts/ExtendedCombatHud.js
scripts/config.js
styles/ActionHUD.css
styles/ECH.css
styles/PortraitHUD.css
templates/extendedCombatHud.html

-- ECH JS --
Removed Debugger, cause it was annoying
-- Action HUD --
Added Classes for Free Action and Reaction
-- Portrait HUD --
Adjusted Margin between Portrait Stat Blocks
-- ECH HUD --
Updated Colors for Action HUD UI
Added Close Button for HUD
-- HTML --
Added Inventory Button that opens Active Players Inventory
Added Close Button to players HUD

Hud Updates

---

scripts/ExtendedCombatHud.js
scripts/config.js
styles/ECH.css

-- CONFIG --
Rigged Color Settings

Color Settings

---

scripts/config.js
styles/PortraitHUD.css

-- Skills Popup --

---

scripts/ExtendedCombatHud.js
scripts/config.js
styles/ECH.css
styles/PortraitHUD.css
templates/extendedCombatHud.html

-- Config.js --
Updated Saves/Skills/Tools to be a generic function
-- Extended Combat Hud --
Mapped Saves/Skills/Tools to be similar format for for Quick Rolls

Saves / Skills / Tools

---

module.json
scripts/ExtendedCombatHud.js
styles/ECH.css
styles/PortraitHUD.css
styles/Tooltip.css
styles/highjacked-window.css
templates/extendedCombatHud.html

Highjack Tooltips

---

scripts/config.js

Fix Them select on Load

---

languages/en.json
scripts/config.js
styles/PortraitHUD.css
styles/theme.css
templates/theme-options.hbs

Added the ability to export a theme. Auto creates json file.
Fixed Theme Dropdown to refresh after exporting theme to show new themes.
Fixed Ability Toggle Button to use text shadow instead of filter brightness.

Export Theme and Abilities Menu Fix

---

styles/ActionHUD.css

Glass effect appears for  bonus action.

Set Secondary

---

styles/ActionHUD.css
styles/theme.css

Updated Movement and Accordion text colors to be more white.

More Color Fixes

---

scripts/ExtendedCombatHud.js
styles/PortraitHUD.css
templates/extendedCombatHud.html

Removed close on hud
Added Minimize on hud
Added Roll InitiativeRoll tooltip

Added Minimize and Tooltip

---

scripts/ExtendedCombatHud.js
styles/ECH.css

If minimized when switching tokens.

Keep State

---

scripts/ExtendedCombatHud.js
templates/extendedCombatHud.html

Added AC and Spell DC localization to pull from DND5E system Localization

System Localization

---

languages/pt-br.json
module.json

- PT-BR translation completed;
- Fixed typo in module.json that caused Foundry to not recognize the translation into pt-BR.

pt-BR translation

---

scripts/core/components/main/movementHud.js

A small change to make it easier to change the way the distance dependent movement hud color is calculated.

Movement color as property

---

scripts/core/components/main/buttonPanel/accordionPanel.js
scripts/core/components/main/buttonPanel/accordionPanelCategory.js

Two small changes to make it easier to implement custom behaviour for subpanels

Accordion subpanel customisation

---

scripts/core/hud.js

Small change to transmit the update context to the onTokenUpdate function, allows for implementation of `isUndo` for the movement hud

Transmit token update context to movement hud onTokenUpdate

---

scripts/core/components/main/movementHud.js

A small change that allows the movementHUD to account for movement undos.

Allow undo for movementHUD
